name: shakti_hormann
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  bloc: ^9.0.0
  freezed_annotation: ^2.4.1
  logger: ^2.6.1
  dartz: ^0.10.1
  path: ^1.9.1
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  provider: ^6.1.5
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  intl: ^0.20.2
  geocoding: ^4.0.0
  connectivity_plus: ^6.1.4
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  animated_custom_dropdown: ^3.1.1
  flutter_bloc: ^9.1.1
  google_mlkit_barcode_scanning: ^0.14.1
  package_info_plus: ^8.3.0
  json_annotation: ^4.8.1
  get_it: ^8.0.3
  http: ^1.4.0
  injectable_generator: ^2.7.0
  go_router: ^16.0.0
  equatable: ^2.0.7
  geolocator: ^14.0.2
  geolocator_platform_interface: ^4.2.6
  permission_handler_platform_interface: ^4.3.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.2
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  dotted_line: ^3.2.3
  flutter_launcher_icons: ^0.14.4
  mobile_scanner: ^3.5.2
  simple_barcode_scanner: ^0.3.0
  font_awesome_flutter: ^10.9.0
  
      


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  injectable_generator: ^2.7.0


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf
          weight: 500

  
  assets:
   
     - assets/images/
     - assets/logo/
flutter_launcher_icons: 
  android: 'ic_launcher'
  image_path: 'assets/logo/hormann-logo-new-1 1.png'
  
  remove_alpha_ios: true
  ios: true  
 