// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH7Aw4cc4P94uFYU1xFdSQ5dyxVm_AyM4',
    appId: '1:397179080765:web:432159cebc6e895e4a1a54',
    messagingSenderId: '397179080765',
    projectId: 'shakti-hormann-16fa4',
    authDomain: 'shakti-hormann-16fa4.firebaseapp.com',
    storageBucket: 'shakti-hormann-16fa4.firebasestorage.app',
    measurementId: 'G-C02FP40PWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZLl_PPxtB6_oE8aanFSSE_L1UYsGJJPA',
    appId: '1:397179080765:android:82ec2ed9cd85e64a4a1a54',
    messagingSenderId: '397179080765',
    projectId: 'shakti-hormann-16fa4',
    storageBucket: 'shakti-hormann-16fa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1BzcV0KNP9VUT0WlHE8F9yNRcQBkB0LM',
    appId: '1:397179080765:ios:011c9f649a226a584a1a54',
    messagingSenderId: '397179080765',
    projectId: 'shakti-hormann-16fa4',
    storageBucket: 'shakti-hormann-16fa4.firebasestorage.app',
    iosBundleId: 'com.example.shaktiHormann',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1BzcV0KNP9VUT0WlHE8F9yNRcQBkB0LM',
    appId: '1:397179080765:ios:011c9f649a226a584a1a54',
    messagingSenderId: '397179080765',
    projectId: 'shakti-hormann-16fa4',
    storageBucket: 'shakti-hormann-16fa4.firebasestorage.app',
    iosBundleId: 'com.example.shaktiHormann',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH7Aw4cc4P94uFYU1xFdSQ5dyxVm_AyM4',
    appId: '1:397179080765:web:bb2337ff8fe1685c4a1a54',
    messagingSenderId: '397179080765',
    projectId: 'shakti-hormann-16fa4',
    authDomain: 'shakti-hormann-16fa4.firebaseapp.com',
    storageBucket: 'shakti-hormann-16fa4.firebasestorage.app',
    measurementId: 'G-LK1KV9X75J',
  );
}
