// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      // case TargetPlatform.windows:
      //   return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyCgzlH6jkXUudsqyvZtFq2CUJvsOb26kRE',
  //   appId: '1:697946700598:web:512cafe9d81f6350479197',
  //   messagingSenderId: '697946700598',
  //   projectId: 'shakti-hormann',
  //   authDomain: 'shakti-hormann.firebaseapp.com',
  //   storageBucket: 'shakti-hormann.firebasestorage.app',
  //   measurementId: 'G-41DKVF3B9X',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfNG07YhCuiM-EIVY91RxhwYRzJxSTJ9I',
    appId: '1:697946700598:android:68f089e86097bb39479197',
    messagingSenderId: '697946700598',
    projectId: 'shakti-hormann',
    storageBucket: 'shakti-hormann.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBAbu2B-QIBCsUZkgIpRnw1hJy-dgRPxOU',
  //   appId: '1:697946700598:ios:ea04f9fb01274854479197',
  //   messagingSenderId: '697946700598',
  //   projectId: 'shakti-hormann',
  //   storageBucket: 'shakti-hormann.firebasestorage.app',
  //   iosBundleId: 'com.example.shaktiHormann',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyBAbu2B-QIBCsUZkgIpRnw1hJy-dgRPxOU',
  //   appId: '1:697946700598:ios:ea04f9fb01274854479197',
  //   messagingSenderId: '697946700598',
  //   projectId: 'shakti-hormann',
  //   storageBucket: 'shakti-hormann.firebasestorage.app',
  //   iosBundleId: 'com.example.shaktiHormann',
  // );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyCgzlH6jkXUudsqyvZtFq2CUJvsOb26kRE',
  //   appId: '1:697946700598:web:e2da833f8ff75e37479197',
  //   messagingSenderId: '697946700598',
  //   projectId: 'shakti-hormann',
  //   authDomain: 'shakti-hormann.firebaseapp.com',
  //   storageBucket: 'shakti-hormann.firebasestorage.app',
  //   measurementId: 'G-RWVDQWNHT8',
  // );
}
